--- #YAML:1.0
name:                Hey-MySQL
version:             3.14
abstract:            ~
license:             ~
author:              
    - Dusty Wilson <cpan-Hey-MySQL@dusty.hey.nu>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBD::mysql:                    2.9004
    DBI:                           1.43
    IO::All:                       0.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
